on:
  push:
    branches:
      - action
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
    - name: Deploy
      id: deploy
      uses: snormore/doctl-app-deploy-action@main
